### ISSUE TITLE
LabeledEnum NameTuple helpers

### ISSUE THREAD

**Issue by jace** [hasgeek/coaster#173]
LabeledEnum offers two syntaxes for labels:

```python
class MY_ENUM(LabeledEnum):
    first = (0, "First")
    second = (0, 'second', "Second')
```

The first syntax creates a value+label pairing, while the second creates a value+(name, title) pairing. The first syntax makes LabeledEnum easy to use in forms, because the declaration is as simple as `choices=MY_ENUM.items()`. The second is trickier:

1. We want to use the second syntax when raw values should not be exposed to the client via an API, because they represent internal database detail.

2. Exposing raw values via forms is okay because the forms are transient and will not be cached by the client. In this case, the declaration becomes `choices=((k, v.title) for k, v in MY_ENUM.items())`. This is verbose and could be reduced into (say) `choices=MY_ENUM.items_by_title()`.

3. However, if values should not be exposed, we need a method (`MY_ENUM.nametitles()`) that returns `((name, title) for name, title in MY_ENUM.values())`

4. The return value from the form will be the name, which needs to be coerced back into the actual value. The enum should provide a `coerce` classmethod.

Resulting form field declaration:

```python
my_choice = forms.RadioField(__("My choice"), choices=MY_ENUM.nametitles(), coerce=MY_ENUM.coerce)
```

**Comment by jace** [comment]
LabeledEnum already has a `value_for` method that does the `coerce` operation described above.

**Comment by jace** [comment]
@iambibhas let's close this and EnumField today. It's trivial.

**Comment by iambibhas** [comment]
@jace the tests are passing now. anything pending for this PR? 

Next step is https://github.com/hasgeek/baseframe/issues/184, right?
