### ISSUE TITLE
Replace GFM module with JS version

### ISSUE THREAD

**Issue by jace** [hasgeek/coaster#182]
Coaster offers a GitHub-flavoured Markdown (GFM) implementation that is a bit of a hack, and not particularly good. It should be replaced with a JavaScript-based version so that the same code can be used server-side and client-side. We already have precedent for this with the UgliPy JS minifier offered by Coaster.

Caveat: JS assets are served to the client side from Baseframe, so Coaster may end up using a different version of the JS library from Baseframe. We could offer an option for replacing the default JS lib, so that Baseframe can offer its version.

**Comment by iambibhas** [comment]
@jace how about http://showdownjs.com/ ? I think they support GFM. [Has table support](https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax) as well.

**Comment by jace** [comment]
Yes, Showdown with GFM mode.

**Comment by iambibhas** [comment]
Forgot to update this. PyExecJS has reached EOL. So can't use it. Only other option is to use Js2Py https://github.com/PiotrDabkowski/Js2Py but after playing around with it, it doesn't seem very reliable. Specially when reading JS from a file. It even threw segfault in couple of cases. Given that I only tried with ShowdownJS.

There is another option which is to use PyV8 directly. But PyV8 doesn't seem to have any recent updates. https://code.google.com/archive/p/pyv8/source/default/commits

**Comment by jace** [comment]
There's an active fork of PyV8 here: https://github.com/buffer/pyv8

**Comment by jace** [comment]
I'm also good to use PyExecJS's recommended solution: just call Node.js.

**Comment by jace** [comment]
As per #74, we will lose Pygments support if we switch to a JS-based Markdown processor, so we'll need to move syntax highlighting to PrismJS or similar.

**Comment by jace** [comment]
This was resolved in #226 using the improved Markdown processing of Python Markdown 3.0.
