### ISSUE TITLE
make_name() doesn't replace line breaks

### ISSUE THREAD

**Issue by iambibhas** [hasgeek/coaster#185]
```
>>> test = """element array.
...
... See also the ag"""
>>> make_name(test)
'element-array-\n\nsee-also-the-ag'
```

This broke couple of videos on HasGeek.TV where the title was copied from funnel and had line break in them, so the `name` generated by [`make_name`](https://github.com/hasgeek/coaster/blob/049d982f2128051e6c2d161c43d5a34b19a57a24/coaster/utils/misc.py#L204) also had newline character, which broke the url.

**Comment by jace** [comment]
Can you add a newline to the strip chars regex and see if that fixes it?

**Comment by jace** [comment]
Actually, just include all non-printable characters. Who knows what will hit us next? See http://www.regular-expressions.info/nonprint.html for syntax, https://www.asciitable.com/ for codes.

Using `[\x01-\x1f]` should work to catch the entire set, but this needs to be tested with Python's regex engine.
