### ISSUE TITLE
ModelView loader method parameters

### ISSUE THREAD

**Issue by jace** [hasgeek/coaster#205]
In `ModelView`, the `loader` method receives a single `kwargs` argument, like so:

```python
class MyView(ModelView):
   def loader(self, kwargs):
       ...
       return obj
```

This was designed with the assumption that `InstanceLoader` will be used all the time, and that `loader`'s method signature should not be responsible for keeping track of a variety of arguments. However, in practice we are writing custom loaders for every class to account for local optimisations in queries. This makes the `kwargs` argument less Pythonic. Consider instead:

```python
class MyView(ModelView):
    def loader(self, doc=None):
       ...
       return obj

    @route('/')
    def index(self):
        return 'index'

    @route('/<doc>')
    def view(self, doc):
        return repr(self.obj)
```

In this case, `loader` receives the same URL parameters as any of the views. A generic loader can still accept `**kwargs` for universal compatibility.

Further, in the `view` example here, the `doc` parameter is superfluous while a new `self.obj` appears unexpectedly. We can change this so that `loader` returns substitutions for URL parameters, and those are passed to the views:

```python
class MyView(ModelView):
    def loader(doc=None):
       ...
       return {'doc': obj}

    @route('/')
    def index(self):
        return 'index'

    @route('/<doc>')
    def view(self, doc):
        return repr(doc)
```

This change is backwards incompatible, but since it's cleaner, we could (a) coordinate a change, or (b) introduce this as `ModelView2`, upgrade all current usage, then deprecate `ModelView` and rename this back.

**Comment by jace** [comment]
There are only two current users: Hasjob and Lastuser. A change can be coordinated.

**Comment by jace** [comment]
This will also apply to `before_request`. Should it also change signature from `kwargs` to `**kwargs`?

**Comment by iambibhas** [comment]
Or we could set `self.kwargs = kwargs` instead of passing it to loader/before_request and they can be used everywhere without this issue of passing it around.

**Comment by jace** [comment]
Also, why is it `before_request` and not `__init__`?

**Comment by jace** [comment]
FWIW, the current syntax where the view gets `**kwargs` derives from how Flask view functions work: they get the parameters from the URL. We kept that for _similarity_. If we move this to `__init__`, we're proposing a serious change to how `ClassView` works -- not necessarily bad, but it's a breaking change.

**Comment by jace** [comment]
We can't do anything interesting in `__init__` because (a) the view isn't fully constructed at the time it is called, and (b) it'll mess with views calling other views by temporarily initialising the class (a valid use case since views are just functions).

https://github.com/hasgeek/coaster/blob/cb25e921b85c868cce9c6c59c647dec9e2698777/coaster/views/classview.py#L163-L174
