### ISSUE TITLE
Provide Flask-SQLAlchemy object as coaster.db

### ISSUE THREAD

**Issue by jace** [hasgeek/coaster#28]
The db object in baseframe is mislocated because some projects may not use baseframe. It should be in coaster instead, with guarantees of being a singleton within the same process.

**Comment by sindhus** [comment]
I wasn't able find any DB object in Baseframe. What should I be looking for?

I only found https://github.com/hasgeek/baseframe/blob/e01471d5d271c53fd579ef49ea9336c17037b457/baseframe/forms/sqlalchemy.py

I ran another search: https://github.com/hasgeek/baseframe/search?utf8=%E2%9C%93&q=%22db.%22

The [changes.rst lists 0.3.0](https://github.com/hasgeek/baseframe/blob/920cb8b9995782edefd813286b02a11ad2a6f051/CHANGES.rst) removed this issue.

**Comment by jace** [comment]
Fixed in 8b4937619051b526e546f2887d9c479cbc1571e0
