### ISSUE TITLE
unused variable 'quality' 

### ISSUE THREAD

**Issue by pranavvp10** [hasgeek/coaster#288]
https://github.com/hasgeek/coaster/blob/d5fb9a222fe8bf862ef8348691a3ed426ba11ab3/coaster/views/decorators.py#L380-L380

**Comment by jace** [comment]
What is the issue?

**Comment by pranavvp10** [comment]
Hi @jace , in the line : https://github.com/hasgeek/coaster/blob/d5fb9a222fe8bf862ef8348691a3ed426ba11ab3/coaster/views/decorators.py#L380-L380

the variable "quality" is not used anywhere in the that program and don't think affects the output. So will it be nice to remove it?
Thanks

**Comment by jace** [comment]
`accept_mimetypes` is a list of 2-tuples. We have to unpack the tuple. To remove the variable, the code will need to be something like `for pair in accept_mimetypes: do_something_with(pair[0])`. This is less readable.

The convention appears to be to use an underscore prefix on such necessary but unused variables, making this one `_quality`. That is a fair ask, and should be part of an audit on the entire repo.

**Comment by pranavvp10** [comment]
okay. thanks.
