### ISSUE TITLE
python setup.py egg_info" failed

### ISSUE THREAD

**Issue by pehrlich** [hasgeek/coaster#56]
Python version: 3.4.3

When installing this package:

> Collecting coaster
  Using cached coaster-0.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/m2/rrqxjb3n5gscyfm4dbdn1kp80000gn/T/pip-build-x_2sybji/coaster/setup.py", line 7, in <module>
        README = unicode(open(os.path.join(here, 'README.rst')).read(), 'utf-8')
    NameError: name 'unicode' is not defined
    
>    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/m2/rrqxjb3n5gscyfm4dbdn1kp80000gn/T/pip-build-x_2sybji/coaster

**Comment by jace** [comment]
Related to #40. There isn't anything specific to Py2 in Coaster, so it's just about having someone address all the little things once.

We should move the discussion into #40.
