### ISSUE TITLE
Replace Flask-Alembic with Flask-Migrate

### ISSUE THREAD

**Issue by jace** [hasgeek/coaster#59]
Flask-Alembic is unmaintained and doesn't work with Flask-Script > 0.5.3, so we've been off the mainstream for a while. Flask-Migrate is newer and better maintained, so we should switch.
1. We have a custom fork of Flask-Alembic that inserts an `init_for` call as required for our apps. Flask-Migrate provides a MigrateCommand for Flask-Script which doesn't know about `init_for`, so we'll to have to override that with our version.
2. Versions have to move from `alembic/versions` to `migrations` in all apps. This unfortunately means it is a breaking change and we have to sync updates with all apps, _or_ write another wrapper that looks in both paths for migrations.
3. The real motivation for doing this is that we want the ability to split migrations between blueprints and keep multiple alembic_version numbers in the database. While this is supported by Alembic, it's not exposed by the wrappers. Reasoning: this will allow splitting up large apps into multiple, independently maintained blueprints (in separate git repositories), all working off the same database but with an independent set of models (except shared models like User from a shared blueprint like `lastuser_core`) and independent versioning for their models.

**Comment by sindhus** [comment]
Info: Blueprints is a Flask concept for making application components and supporting common patterns within a application. More [here](http://flask.pocoo.org/docs/0.10/blueprints/). Also advised to see [Lastuser](http://github.com/hasgeek/lastuser) code layout.

**Comment by jace** [comment]
Please file tickets in all apps with the same title and the following text: `Refer to hasgeek/coaster#59`.

**Comment by jace** [comment]
Steps to switch from Flask-Alembic to Flask-Migrate:

1. Switch to Coaster's `flask-migrate` branch
2. Import and enable the migrate extension in your app's `__init__.py` (after app config and `db.init_app(app)`)
3. Add Flask-Migrate to `requirements.txt`
4. Run `manage.py db init` to create a `migrations` folder
5. `rm migrations/versions` (remove empty versions folder)
6. `git add migrations`
7. `git mv alembic/versions migrations` (move over existing migrations)
8. `git rm -rf alembic` (remove flask-alembic config)
9. `git rm alembic.ini` (a new copy will be in the migrations folder)
