### ISSUE TITLE
Docs: Inconsistencies in SQLAlchemy patterns page

### ISSUE THREAD

**Issue by ghost** [hasgeek/coaster#63]
The [docs for SQLAlchemy patterns provided by Coaster](http://coaster.readthedocs.org/en/latest/sqlalchemy.html) in `coaster.sqlalchemy`  is sort of inconsistent what's available in [the code](https://github.com/hasgeek/coaster/blob/master/coaster/sqlalchemy.py). 

The docs page doesn't list Query class docs and some classes are missing sample use cases.
For the latter, we could with do with some sample use cases, just a matter of writing them. 

However the former is tricky. 

**Context**: we use readthedocs to generate this documentation. So running `git submodule update --init --recursive` brings in the theme dir required for you to compile docs locally with `cd docs && make html`. The compiled HTML files are `../docs/build/html`

At the moment, I am unable to view documentation added to any new class in the `../coaster/sqlalchemy.py` file. Even copy pasting an existing class and renaming it is not picked up by readthedocs despite a fresh make. Only changes to existing classes (whose docs are being picked up by readthedocs) are picked up by readthedocs.

**Comment by jace** [comment]
Closing this as it seems to be about ReadTheDocs syncing correctly, and not an issue in Coaster itself.
