### ISSUE TITLE
Make Flask-debugtoolbar available

### ISSUE THREAD

**Issue by sindhus** [hasgeek/coaster#65]
It would be handy to have [Flask-debugtoolbar]() available across all our Flask apps. Would be very handy to be able to see [SQL queries being executed with a request](http://flask-debugtoolbar.readthedocs.org/en/latest/panels.html#sqlalchemy), especially in Hasjob.

**Comment by jace** [comment]
This is unrelated to Coaster. It should be on the individual projects, or globally enabled from Baseframe.
